import React, { useEffect, useState } from "react";
import CustomerHistorySection from "./CustomerHistorySection";
import { asConsultHistory, asCustomers, asSalesHistory, previousAsHistory } from "./asMockData";

const empty = { customer:"", phone:"", mobile:"", address:"", brand:"", product:"", category:"", serial:"", purchaseDate:"", market:"", symptom:"", memo:"" };

export default function AsCreateModal({ onClose, onCreate }) {
  const [query,setQuery] = useState({name:"",mobile:""});
  const [searched,setSearched] = useState(false);
  const [matched,setMatched] = useState([]);
  const [form,setForm] = useState(empty);
  const [errors,setErrors] = useState({});
  const [selectedId,setSelectedId] = useState("");
  useEffect(() => { const key=(event)=>event.key==="Escape"&&onClose(); window.addEventListener("keydown",key); document.body.classList.add("modal-open"); return()=>{window.removeEventListener("keydown",key);document.body.classList.remove("modal-open");}; },[onClose]);
  const update=(key,value)=>{ if((key==="phone"||key==="mobile")&&!/^[0-9-]*$/.test(value))return; if(key==="serial")value=value.replace(/\s/g,""); setForm(current=>({...current,[key]:value})); setErrors(current=>({...current,[key]:""})); };
  const search=()=>{ const name=query.name.trim(),mobile=query.mobile.replace(/\D/g,""); if(!name&&!mobile){setSearched(false);setMatched([]);return;} setMatched(asCustomers.filter(customer=>(!name||customer.name.includes(name))&&(!mobile||`${customer.phone}${customer.mobile}`.replace(/\D/g,"").endsWith(mobile))).map(customer=>customer.id));setSearched(true);setSelectedId(""); };
  const copy=(row,kind)=>{ if(kind==="as"&&(form.symptom||form.memo)&&!window.confirm("기존 증상 정보를 불러오시겠습니까?"))return; if(kind==="consult"&&form.memo&& !window.confirm("상담문의 내용을 AS 상담 메모에 추가하시겠습니까?"))return; setSelectedId(row.id);setForm(current=>({...current,customer:row.name,phone:row.phone,mobile:row.mobile,address:row.address,brand:row.brand,product:row.product,category:row.category,serial:row.serial,purchaseDate:row.purchaseDate,market:row.market,symptom:kind==="as"?row.symptom:current.symptom,memo:kind==="consult"?`${current.memo}${current.memo?"\n":""}${row.detail}`:current.memo}));setErrors({}); };
  const submit=(event)=>{event.preventDefault();const next={};[["customer","고객명"],["mobile","핸드폰"],["brand","브랜드"],["product","상품명"],["symptom","증상 요약"]].forEach(([key,label])=>{if(!form[key].trim())next[key]=`${label}을 입력해 주세요.`;}); if(form.phone&&!/^[0-9-]+$/.test(form.phone))next.phone="숫자와 하이픈만 입력할 수 있습니다.";if(form.mobile&&!/^[0-9-]+$/.test(form.mobile))next.mobile="숫자와 하이픈만 입력할 수 있습니다.";if(form.purchaseDate&&form.purchaseDate>new Date().toISOString().slice(0,10))next.purchaseDate="미래 날짜는 입력할 수 없습니다.";setErrors(next);if(!Object.keys(next).length)onCreate(form);};
  const rows=(items)=>searched?items.filter(item=>matched.includes(item.customerId)):[];
  const field=(key,label,required,type="text")=><label className="as-create-field"><span>{required&&<em>*</em>}{label}</span>{key==="brand"?<select value={form.brand} onChange={event=>update("brand",event.target.value)}><option value="">선택</option><option>Balmuda</option><option>Vermicular</option><option>Moon</option><option>기타</option></select>:<input type={type} value={form[key]} onChange={event=>update(key,event.target.value)}/>} {errors[key]&&<small>{errors[key]}</small>}</label>;
  return <div className="as-create-layer"><section className="as-create-modal" role="dialog" aria-modal="true" aria-labelledby="as-create-title">
    <header><h2 id="as-create-title">AS 신규 접수 화면</h2><button type="button" onClick={onClose} aria-label="닫기">×</button></header>
    <form className="as-create-grid" onSubmit={submit} noValidate><div className="as-create-left">
      <section className="as-create-section"><h3>고객정보 검색 <small>고객명, 핸드폰 번호 AND 조건 검색</small></h3><div className="as-customer-search"><label><span>고객명</span><input value={query.name} placeholder="구매자/수취인 동시검색" onChange={event=>setQuery(current=>({...current,name:event.target.value}))}/></label><label><span>핸드폰</span><input value={query.mobile} placeholder="끝자리 검색 지원" onChange={event=>setQuery(current=>({...current,mobile:event.target.value}))}/></label><button type="button" onClick={search}>검색</button></div></section>
      <section className="as-create-section"><h3>AS 고객정보 입력 <small>판매이력이 검색되지 않을 경우 직접 입력</small></h3><div className="as-create-fields">{field("customer","고객명",true)}{field("phone","전화")}{field("mobile","핸드폰",true)}{field("address","주소")}</div></section>
      <section className="as-create-section"><h3>제품정보 입력 <small>판매이력이 검색되지 않을 경우 직접 입력</small></h3><div className="as-create-fields">{field("brand","브랜드",true)}{field("product","상품명",true)}{field("category","상품분류")}{field("serial","S/N")}{field("purchaseDate","고객구매일",false,"date")}{field("market","구매마켓명")}</div></section>
      <section className="as-create-section"><h3>증상 및 메모</h3><div className="as-create-fields as-create-fields--single"><label className="as-create-field"><span><em>*</em>증상 요약</span><input maxLength={30} value={form.symptom} placeholder="증상을 키워드 중심으로 작성(최대30자)" onChange={event=>update("symptom",event.target.value)}/><b>{form.symptom.length}/30</b>{errors.symptom&&<small>{errors.symptom}</small>}</label><label className="as-create-field as-create-field--memo"><span>AS 상담 메모</span><textarea value={form.memo} placeholder="AS 접수시 제품 및 고객 특이사항을 메모 하십시오" onChange={event=>update("memo",event.target.value)}/></label></div><div className="as-create-submit"><button type="submit">신규 AS건 작성 완료</button></div></section>
    </div><div className="as-create-right"><CustomerHistorySection title="고객 판매이력 검색 결과" kind="sales" rows={rows(asSalesHistory)} searched={searched} selectedId={selectedId} onSelect={row=>copy(row,"sale")}/><CustomerHistorySection title="고객 A/S이력 검색 결과" kind="as" rows={rows(previousAsHistory)} searched={searched} selectedId={selectedId} onSelect={row=>copy(row,"as")}/><CustomerHistorySection title="고객 상담문의이력 검색 결과" kind="consultations" rows={rows(asConsultHistory)} searched={searched} selectedId={selectedId} onSelect={row=>copy(row,"consult")}/></div></form>
  </section></div>;
}
