import React, { useEffect, useMemo, useState } from "react";
import AsCreateModal from "./AsCreateModal";
import { asCountLabels, asStatuses, initialAsRows } from "./asMockData";
import { recordPreviewActivity } from "./services/activityBridge";

const fields={no:"No.",manager:"담당자",brand:"브랜드",product:"상품명",serial:"S/N",symptom:"증상",customer:"고객명",contact:"연락처"};
const columns=[["no","No."],["changed","최종변경"],["status","상태"],["manager","담당자"],["brand","브랜드"],["product","상품명"],["serial","S/N"],["symptom","증상"],["customer","고객명"],["contact","연락처"],["inbound","입고일"],["outbound","출고일"],["visit","방문"],["visitDate","방문예정일"]];

export default function AsManagement(){
 const [rows,setRows]=useState(initialAsRows),[counts,setCounts]=useState(asCountLabels),[status,setStatus]=useState("전체"),[field,setField]=useState("no"),[input,setInput]=useState(""),[keyword,setKeyword]=useState(""),[recent,setRecent]=useState(false),[page,setPage]=useState(1),[checked,setChecked]=useState(()=>new Set()),[selected,setSelected]=useState(""),[modal,setModal]=useState(false),[toast,setToast]=useState("");
 const filtered=useMemo(()=>rows.filter(row=>(status==="전체"||row.status===status)&&(!keyword||String(row[field]).toLowerCase().includes(keyword.toLowerCase()))).sort((a,b)=>recent?b.changed.localeCompare(a.changed):b.no-a.no),[rows,status,keyword,field,recent]);
 const pageRows=filtered.slice((page-1)*20,page*20),all=pageRows.length>0&&pageRows.every(row=>checked.has(row.id));
 const search=()=>{setKeyword(input.trim());setPage(1);}; useEffect(()=>{const key=event=>{if(event.key==="F8"&&!modal){event.preventDefault();search();}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[input,modal]);
 const toggleAll=()=>setChecked(current=>{const next=new Set(current);pageRows.forEach(row=>all?next.delete(row.id):next.add(row.id));return next;}); const toggle=id=>setChecked(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});
 const create=form=>{const now=new Date(),stamp=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")} ${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}:${String(now.getSeconds()).padStart(2,"0")}`;setRows(current=>[{id:`AS-NEW-${Date.now()}`,no:current.length+1,changed:stamp,status:"AS접수",manager:"현재사용자",brand:form.brand,product:form.product,serial:form.serial||"-",symptom:form.symptom,customer:form.customer,contact:form.mobile,inbound:"-",outbound:"-",visit:"-",visitDate:"-"},...current]);setCounts(current=>({...current,전체:current.전체+1,AS접수:current.AS접수+1}));setStatus("전체");setPage(1);setModal(false);setToast("신규 AS건이 프론트 임시 데이터로 등록되었습니다.");recordPreviewActivity("as","create");window.setTimeout(()=>setToast(""),2500);};
 return <section className="as-management"><header><h1>A/S 목록</h1><span>프론트엔드 mock 데이터</span></header><div className="as-toolbar"><button className="primary" type="button" onClick={()=>setModal(true)}>신규 AS 작성</button><form onSubmit={event=>{event.preventDefault();search();}}><select value={field} onChange={event=>setField(event.target.value)}>{Object.entries(fields).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input value={input} placeholder="검색어를 입력하세요" onChange={event=>setInput(event.target.value)}/><button className="primary">검색(F8)</button><button type="button" onClick={()=>{setInput("");setKeyword("");setPage(1);}}>초기화</button></form><label><input type="checkbox" checked={recent} onChange={event=>setRecent(event.target.checked)}/>최근수정건 위로</label><strong>{checked.size}건 선택</strong></div>
 <div className="as-status-tabs"><button className={status==="전체"?"active":""} onClick={()=>{setStatus("전체");setPage(1);}}>전체 <span>{counts.전체.toLocaleString()}건</span></button>{asStatuses.map(item=><button key={item} className={status===item?"active":""} onClick={()=>{setStatus(item);setPage(1);}}>{item} <span>{counts[item].toLocaleString()}건</span></button>)}</div>
 <div className="as-table-wrap"><table className="as-table"><thead><tr><th><input type="checkbox" checked={all} onChange={toggleAll}/></th>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{pageRows.map(row=><tr key={row.id} className={selected===row.id?"selected":""} onClick={()=>setSelected(row.id)}><td><input type="checkbox" checked={checked.has(row.id)} onClick={event=>event.stopPropagation()} onChange={()=>toggle(row.id)}/></td>{columns.map(([key])=><td key={key} title={String(row[key])}>{key==="status"?<span className={`as-badge as-badge--${row.status}`}>{row.status}</span>:row[key]}</td>)}</tr>)}</tbody></table></div>
 <nav className="as-pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>이전</button>{Array.from({length:30},(_,i)=>i+1).map(number=><button key={number} className={page===number?"active":""} onClick={()=>setPage(number)}>{number}</button>)}<button disabled={page===30} onClick={()=>setPage(page+1)}>다음</button></nav>{modal&&<AsCreateModal onClose={()=>setModal(false)} onCreate={create}/>} {toast&&<div className="product-toast" role="status">{toast}</div>}</section>;
}
