import React,{useState}from"react";
import{Modal}from"./components/common/CommonUI";
import MaskedText from"./components/common/MaskedText";

const today=()=>new Date().toISOString().slice(0,10);
const empty={name:"",userId:"",password:"",passwordConfirm:"",store:"",role:"직원",phone:"",email:"",joined:today(),approvalStatus:"pending",employmentStatus:"active",note:""};
const approvalOptions=[["pending","대기"],["approved","승인"]];
const employmentOptions=[["active","재직"],["resigned","퇴사"]];

export default function EmployeeModal({mode="create",employee,userIds,onClose,onSave,onEdit}){
 const initial={...empty,...employee,password:"",passwordConfirm:""};
 const[form,setForm]=useState(initial),[errors,setErrors]=useState({}),[changePassword,setChangePassword]=useState(false);
 const edit=mode!=="view",dirty=edit&&JSON.stringify(form)!==JSON.stringify(initial);
 const set=(key,value)=>setForm(current=>({...current,[key]:value}));
 const input=(key,label,type="text",locked=false)=><label className="employee-field"><span>{label}</span>{mode==="view"&&key==="phone"?<div className="employee-masked-value"><MaskedText value={form.phone} type="phone" allowReveal/></div>:<input type={type} value={form[key]||""} readOnly={!edit||locked} onChange={event=>set(key,event.target.value)}/>} {errors[key]&&<small>{errors[key]}</small>}</label>;
 const select=(key,label,options)=><label className="employee-field"><span>{label}</span><select value={form[key]} disabled={!edit} onChange={event=>set(key,event.target.value)}>{options.map(option=>Array.isArray(option)?<option key={option[0]} value={option[0]}>{option[1]}</option>:<option key={option}>{option}</option>)}</select></label>;
 function submit(event){event.preventDefault();const next={};if(!form.name.trim())next.name="이름은 필수입니다.";if(!/^[A-Za-z0-9._]+$/.test(form.userId))next.userId="아이디는 영문, 숫자, 점, 밑줄만 사용할 수 있습니다.";if(mode==="create"&&userIds.includes(form.userId.toLowerCase()))next.userId="이미 사용 중인 아이디입니다.";if(!form.store.trim())next.store="매장은 필수입니다.";if(!/^\d{2,3}-\d{3,4}-\d{4}$/.test(form.phone))next.phone="전화번호 형식을 확인하십시오.";if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))next.email="이메일 형식을 확인하십시오.";if(!form.joined)next.joined="입사일은 필수입니다.";if(mode==="create"||changePassword){if(form.password.length<4)next.password="비밀번호는 4자 이상 입력하십시오.";if(form.password!==form.passwordConfirm)next.passwordConfirm="비밀번호가 일치하지 않습니다."}setErrors(next);if(Object.keys(next).length)return;const{password,passwordConfirm,...safeEmployee}=form;onSave(safeEmployee)}
 return <Modal title={mode==="create"?"신규 직원 등록":mode==="edit"?"직원 수정":"직원 상세"} onClose={onClose} dirty={dirty}><form className={`employee-modal employee-modal--${mode}`} onSubmit={submit}><div className="employee-form-grid">{input("name","이름")}{input("userId","아이디","text",mode==="edit")}{mode==="create"&&<>{input("password","비밀번호","password")}{input("passwordConfirm","비밀번호 확인","password")}</>}{input("store","매장")}{select("role","직책",["직원","부매니저","매니저"])}{input("phone","전화번호")}{input("email","이메일","email")}{input("joined","입사일","date")}{select("approvalStatus","승인상태",approvalOptions)}{select("employmentStatus","재직상태",employmentOptions)}{mode==="view"&&<>{input("registeredAt","등록일")}{input("updatedAt","최종 수정일")}{employee?.resignedAt&&input("resignedAt","퇴사일")}</>}{mode==="edit"&&<><label className="employee-password-toggle"><input type="checkbox" checked={changePassword} onChange={event=>setChangePassword(event.target.checked)}/>비밀번호 변경</label>{changePassword&&<>{input("password","새 비밀번호","password")}{input("passwordConfirm","비밀번호 확인","password")}</>}</>}<label className="employee-field employee-field--note"><span>비고</span><textarea value={form.note||""} readOnly={!edit} onChange={event=>set("note",event.target.value)}/></label></div>{mode==="view"&&employee?.history?.length>0&&<section className="employee-history"><h3>변경 이력</h3>{employee.history.slice().reverse().map((item,index)=><div key={`${item.occurredAt}-${index}`}><strong>{item.action}</strong><span>{item.occurredAt}</span><p>{item.description}</p></div>)}</section>}<footer>{mode==="view"?<button type="button" className="primary" onClick={onEdit}>수정</button>:<button className="primary">{mode==="create"?"직원등록":"저장"}</button>}<button type="button" onClick={onClose}>닫기</button></footer></form></Modal>
}
