import React,{useEffect,useState}from"react";
import{markets,salesStatuses}from"./salesMockData";
import MarketplaceSelector from "./MarketplaceSelector";

function Shell({title,onClose,children,wide=false}){useEffect(()=>{const key=e=>e.key==="Escape"&&onClose();window.addEventListener("keydown",key);document.body.classList.add("modal-open");return()=>{window.removeEventListener("keydown",key);document.body.classList.remove("modal-open")}},[onClose]);return <div className="sales-modal-layer"><section className={`sales-modal${wide?" sales-modal--wide":""}`} role="dialog" aria-modal="true"><header><h2>{title}</h2><button onClick={onClose}>×</button></header>{children}</section></div>}
const validExcel=file=>file&&/\.(xls|xlsx)$/i.test(file.name);
const Notice=({warning=false})=><div className={`sales-upload-notice${warning?" warning":""}`}><strong>{warning?"업로드 즉시 물류팀으로 발주요청 처리됩니다.":"파일 등록 안내"}</strong><p>XLS, XLSX 파일만 허용합니다. HTML/CSV 또는 비정상 Excel binary 파일은 처리할 수 없습니다.</p><p>신규 마켓이나 양식 변경 시 환경설정에서 매핑을 변경하십시오.</p></div>;

export function SalesCreateModal({onClose,onCreate}){const empty={market:"",orderNo:"",orderer:"",orderPhone:"",orderMobile:"",recipient:"",recipientPhone:"",recipientMobile:"",zip:"",address:"",brand:"",category:"",product:"",quantity:"1",option:"",revenue:"0",salePrice:"0",promiseDate:"",memo:"",delivery:""};const[form,setForm]=useState(empty),[errors,setErrors]=useState({});const update=(key,value)=>{if(["orderPhone","orderMobile","recipientPhone","recipientMobile"].includes(key)&&!/^[0-9-]*$/.test(value))return;setForm(c=>({...c,[key]:value}));setErrors(c=>({...c,[key]:""}))};const submit=e=>{e.preventDefault();const next={};[["market","마켓명"],["orderer","주문자"],["recipient","수취인"],["brand","브랜드"],["product","상품명"]].forEach(([k,l])=>{if(!form[k].trim())next[k]=`${l}을 입력해 주세요.`});if(Number(form.quantity)<1)next.quantity="수량은 1 이상이어야 합니다.";if(Number(form.revenue)<0||Number(form.salePrice)<0)next.revenue="금액은 0 이상이어야 합니다.";setErrors(next);if(!Object.keys(next).length)onCreate(form)};const field=(key,label,required,type="text")=><label className="sales-form-field"><span>{required&&<em>*</em>}{label}</span>{key==="market"?<select value={form.market} onChange={e=>update(key,e.target.value)}><option value="">선택</option>{markets.map(x=><option key={x}>{x}</option>)}</select>:key==="brand"?<select value={form.brand} onChange={e=>update(key,e.target.value)}><option value="">선택</option>{["Balmuda","Vermicular","Moon","기타"].map(x=><option key={x}>{x}</option>)}</select>:<input type={type} value={form[key]} onChange={e=>update(key,e.target.value)}/>} {errors[key]&&<small>{errors[key]}</small>}</label>;
return <Shell title="판매 데이터 수기 등록" onClose={onClose}><form className="sales-create-form" onSubmit={submit} noValidate><h3>주문 정보</h3><div>{field("market","마켓명",true)}{field("orderNo","주문번호")}</div><h3>주문자 정보</h3><div>{field("orderer","주문자",true)}{field("orderPhone","전화번호")}{field("orderMobile","핸드폰")}</div><h3>수취인 정보</h3><div>{field("recipient","수취인",true)}{field("recipientPhone","전화번호")}{field("recipientMobile","핸드폰")}{field("zip","우편번호")}{field("address","수취인 주소")}</div><h3>상품 정보</h3><div>{field("brand","브랜드",true)}{field("category","상품구분")}{field("product","상품명",true)}{field("quantity","수량",true,"number")}{field("option","옵션")}{field("revenue","매출액",false,"number")}{field("salePrice","판매가",false,"number")}{field("promiseDate","고객약속일",false,"date")}</div><label className="sales-form-text"><span>메모</span><textarea value={form.memo} onChange={e=>update("memo",e.target.value)}/></label><label className="sales-form-text"><span>배송메시지</span><textarea value={form.delivery} onChange={e=>update("delivery",e.target.value)}/></label><footer><button className="primary">판매 데이터 입력</button></footer></form></Shell>}

export function MergeToolModal({onClose,onNotice}){const[market,setMarket]=useState(""),[description,setDescription]=useState(""),[file,setFile]=useState(null),[items,setItems]=useState([]),[checked,setChecked]=useState(new Set()),[error,setError]=useState("");const upload=()=>{if(!market){setError("마켓을 선택하십시오.");return}if(!validExcel(file)){setError("XLS 또는 XLSX 파일을 선택하십시오.");return}setItems(c=>[{id:Date.now(),date:new Date().toLocaleString("ko-KR"),market,manager:"현재사용자",note:description||file.name},...c]);setError("")};return <Shell title="데이터 통합 도구" onClose={onClose} wide><div className="sales-merge-grid"><section><Notice/><MarketplaceSelector value={market} onChange={setMarket} onNotice={onNotice}><label>파일설명<input value={description} onChange={e=>setDescription(e.target.value)}/></label><label>파일선택<input type="file" accept=".xls,.xlsx" onChange={e=>setFile(e.target.files[0])}/></label>{error&&<small>{error}</small>}<button className="primary" onClick={upload}>마켓 데이터 업로드</button></MarketplaceSelector></section><section><h3>임시 취합 데이터 목록</h3><table><thead><tr><th></th><th>등록일시</th><th>마켓명</th><th>담당자</th><th>비고</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><input type="checkbox" checked={checked.has(item.id)} onChange={()=>setChecked(c=>{const n=new Set(c);n.has(item.id)?n.delete(item.id):n.add(item.id);return n})}/></td><td>{item.date}</td><td>{item.market}</td><td>{item.manager}</td><td>{item.note}</td></tr>)}</tbody></table><footer><button onClick={()=>onNotice("프론트 개발 모드에서는 다운로드하지 않습니다.")}>체크 데이터 통합 다운로드</button><button onClick={()=>{setItems(c=>c.filter(x=>!checked.has(x.id)));setChecked(new Set())}}>임시 취합 데이터 삭제</button></footer></section></div></Shell>}

function UploadModal({title,onClose,onUpload,integrated=false}){const[market,setMarket]=useState(""),[file,setFile]=useState(null),[error,setError]=useState(""),[result,setResult]=useState(null);const upload=()=>{if(!integrated&&!market){setError("마켓을 선택하십시오.");return}if(!validExcel(file)){setError("XLS 또는 XLSX 파일을 선택하십시오.");return}setError("");setResult(integrated?{total:25,normal:23,duplicate:1,error:1}:{total:5,normal:5,duplicate:0,error:0});onUpload({market:market||"통합 마켓",count:integrated?3:2,status:integrated?"발주요청":"판매접수"})};return <Shell title={title} onClose={onClose}><div className="sales-upload-body"><Notice warning={integrated}/>{!integrated&&<label>마켓선택<select value={market} onChange={e=>setMarket(e.target.value)}><option value="">선택</option>{markets.map(x=><option key={x}>{x}</option>)}</select></label>}<label>파일선택<input type="file" accept=".xls,.xlsx" onChange={e=>setFile(e.target.files[0])}/></label>{error&&<small>{error}</small>}<button className="primary" onClick={upload}>마켓 데이터 업로드</button>{result&&<div className="sales-upload-result"><span>전체 <b>{result.total}건</b></span><span>정상 <b>{result.normal}건</b></span><span>중복 <b>{result.duplicate}건</b></span><span>오류 <b>{result.error}건</b></span></div>}</div></Shell>}
export const IntegratedMarketUploadModal=props=><UploadModal {...props} integrated title="마켓통합 데이터 등록(자동발주)"/>;
export const MarketUploadModal=props=><UploadModal {...props} title="마켓 데이터 일괄 등록"/>;
export function StatusChangeModal({onClose,onConfirm}){const[status,setStatus]=useState("판매접수");return <Shell title="선택 주문 상태변경" onClose={onClose}><div className="sales-status-change"><label>변경 상태<select value={status} onChange={e=>setStatus(e.target.value)}>{salesStatuses.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" onClick={()=>onConfirm(status)}>확인</button></div></Shell>}
